language: perl
sudo: false

addons:
  apt:
    packages:
      - libapr1-dev
      - libaprutil1-dev

install:
  - perlbrew list
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n

perl:
  - "5.18-shrplib"
  - "5.20-shrplib"

script:
  - dzil install -v --install-command 'cpanm -v .'
  - alien-apache24-install-mod_perl
