language: perl
sudo: false

addons:
  apt:
    packages:
      - libapr1-dev
      - libaprutil1-dev

install:
  - perlbrew list
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n

perl:
  - "5.8"
  - "5.10"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"

script:
  - dzil install -v --install-command 'cpanm -v .'
  - alien-apache24-install-mod_perl
