language: perl
sudo: true
cache: ccache

install:
  - perlbrew list
  - bash corpus/travis_helper.sh
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n

perl:
  - "5.18-shrplib"
  - "5.20-shrplib"

script:
  - dzil install -v --install-command 'cpanm -v .'
  - echo 'y' | alien-apache24-install-mod_perl
